### ISSUE TITLE
Unable to run NPM run build

### ISSUE THREAD

**Issue by benhbell** [GDGToulouse/devfest-theme-hugo#26]
Hi! PopOS user here with hugo installed. When running through the install process for this theme I get the following error after running npm run build Pop!_OS 21.04
```
at /themes/devfest-theme-hugo/static/theme.css:1:41771
    at Parser.error (/home/ceegee/Dev/ben/belista.party/themes/devfest-theme-hugo/node_modules/postcss-values-parser/lib/parser.js:127:11)
    at Parser.operator (/home/ceegee/Dev/ben/belista.party/themes/devfest-theme-hugo/node_modules/postcss-values-parser/lib/parser.js:183:18)
    at Parser.parseTokens (/home/ceegee/Dev/ben/belista.party/themes/devfest-theme-hugo/node_modules/postcss-values-parser/lib/parser.js:245:14)
    at Parser.loop (/home/ceegee/Dev/ben/belista.party/themes/devfest-theme-hugo/node_modules/postcss-values-parser/lib/parser.js:132:12)
    at Parser.parse (/home/ceegee/Dev/ben/belista.party/themes/devfest-theme-hugo/node_modules/postcss-values-parser/lib/parser.js:51:17)
    at parse (/home/ceegee/Dev/ben/belista.party/themes/devfest-theme-hugo/node_modules/postcss-custom-properties/index.cjs.js:47:30)
    at /home/ceegee/Dev/ben/belista.party/themes/devfest-theme-hugo/node_modules/postcss-custom-properties/index.cjs.js:333:24
    at /home/ceegee/Dev/ben/belista.party/themes/devfest-theme-hugo/node_modules/postcss/lib/container.js:194:18
    at /home/ceegee/Dev/ben/belista.party/themes/devfest-theme-hugo/node_modules/postcss/lib/container.js:139:18
    at Rule.each (/home/ceegee/Dev/ben/belista.party/themes/devfest-theme-hugo/node_modules/postcss/lib/container.js:105:16) {
  postcssNode: Declaration {
    raws: { before: '', between: ':' },
    type: 'decl',
    parent: Rule {
      raws: [Object],
      type: 'rule',
      nodes: [Array],
      parent: [AtRule],
      source: [Object],
      selector: '.section.schedule main>section.schedule .day',
      lastEach: 1,
      indexes: [Object]
    },
    source: { start: [Object], input: [Input], end: [Object] },
    prop: '-ms-grid-rows',
    value: '4em (4.5em)[calc(var(--end) - 1)]'
  }
}
ERROR: "build:style" exited with 1.
```

**Comment by ice6** [comment]
same problem. toolchain is too old.

**Comment by vviaan** [comment]
How can i build this correctly? Almost every dependency is deprecated.
